### paulirotations.jl
##
# A file for Pauli rotation gates, i.e., gates that are generated by a Pauli string.
# For example PauliRotation(:X, 2)  ->  RX_2(θ) = exp(-i θ/2 X_2) is a Pauli rotation gate.
##
###

"""
A type for a Pauli rotation gate carrying the gate generator and the qubit indices on which it acts.
"""
struct PauliRotation <: ParametrizedGate
    symbols::Vector{Symbol}
    qinds::Vector{Int}

    @doc """
        PauliRotation(symbols::Vector{Symbol}, qinds::Vector{Int})
        PauliRotation(symbol::Symbol, qind::Int)

    A parametrized Pauli rotation generated by the Pauli string `symbols` acting on the qubits `qinds`.
    For example PauliRotation(:X, 2) or PauliRotation([:X, :Y], [1, 2]).
    We follow the convention that those rotation are equivalent by conjugation of 
    ```math
    e^{-i θ/2 P}
    ```
    where `P` is the corresponding Pauli operator.
    """
    function PauliRotation(symbols, qinds)

        # turn symbols into vectors
        if isa(symbols, Symbol)
            symbols = [symbols]
        else
            symbols = vec(collect(symbols))
        end

        # check that the symbols are valid Pauli symbols
        _paulisymbolcheck(symbols)

        # turn qinds into vectors
        qinds = vec(collect(qinds))
        # check that the qubit indices are positive integers
        _qinds_check(qinds)

        # check that the number of symbols matches the number of qubits
        _qindslengthcheck(symbols, qinds)

        return new(symbols, qinds)
    end
end

function _paulisymbolcheck(symbols)
    if any(s -> s ∉ (:I, :X, :Y, :Z), symbols)
        throw(ArgumentError("Symbols must be `:I`, `:X`, `:Y`, or `:Z`. Got $symbols."))
    end
end

function _qindslengthcheck(symbols, qinds)
    if length(symbols) != length(qinds)
        throw(ArgumentError(
            "The number of symbols must match the number of qubits. " *
            "Got $(length(symbols)) symbols and $(length(qinds)) qubits."
        ))
    end
end

"""
    PauliRotation(symbols, qinds, theta)

Constructor for a frozen `PauliRotation` generated by the Pauli string `symbols` acting on the qubits `qinds`,
and with fixed parameter `theta`.
"""
function PauliRotation(symbols, qinds, theta)
    return FrozenGate(PauliRotation(symbols, qinds), theta)
end


"""
    tomatrix(gate::PauliRotation, theta)

Compute the unitary matrix for the `PauliRotation` gate with parameter `theta` in the computational 0/1 basis.
This is done by computing the matrix `U = cos(θ/2) I - i sin(θ/2) P` where `P` is the Pauli matrix corresponding to the `symbols`.
The returned unitary is returned in Schrödinger picture form.
"""
function tomatrix(gate::PauliRotation, theta)

    nqubits = length(gate.qinds)
    pauli_basis_vec = getpaulibasis(nqubits)

    # The indices of the pauli matrix are sorted in ascending order
    sorted_indices = sortperm(gate.qinds)
    pauli = gate.symbols[sorted_indices]

    # These pauli matrices are normalized by sqrt(2)^nqubits
    pauli_mat = sqrt(2)^nqubits * pauli_basis_vec[symboltoint(pauli)+1]

    id = I(2^nqubits)

    U = cos(theta / 2) * id - 1.0im * sin(theta / 2) * pauli_mat

    return U
end


"""
    commutes(gate::PauliRotation, pstr::PauliString)

Check if a `PauliRotation` commutes with a `PauliString`.
"""
function commutes(gate::PauliRotation, pstr::PauliString)
    return commutes(gate, pstr.term)
end

"""
    commutes(gate::PauliRotation, pstr::Integer)

Check if a `PauliRotation` commutes with an integer Pauli string.
"""
function commutes(gate::PauliRotation, pstr::PauliStringType)
    # calculate the integer representation of the gate generator for faster computation
    generator_mask = symboltoint(typeof(pstr), gate.symbols, gate.qinds)
    return commutes(generator_mask, pstr)
end




