###
##
# The circuits Propaq benchmarks in its paper (arXiv:2609.07730), as PauliPropagation circuits.
##
###

using PauliPropagation

"""
    tfim2d(nx, ny, nsteps; J=1.0, h=0.5, dt=0.1)

Trotterized time evolution of a 2D transverse-field Ising model on an `nx` by `ny` grid,
`H = J ∑_<ij> Z_i Z_j + h ∑_i X_i`. Returns the circuit and its parameters.
"""
function tfim2d(nx::Int, ny::Int, nsteps::Int; J::Real=1.0, h::Real=0.5, dt::Real=0.1)
    nq = nx * ny
    topo = rectangletopology(nx, ny)
    circuit = tfitrottercircuit(nq, nsteps; topology=topo)

    # PauliRotation is exp(-i θ/2 P), so a time step dt of a term with coefficient c is θ = 2 c dt
    thetas = [gate isa PauliRotation && length(gate.qinds) == 2 ? 2 * J * dt : 2 * h * dt
              for gate in circuit if gate isa ParametrizedGate]

    return circuit, thetas
end

"""
    tfim2dobservable(nx, ny)

The single-`Z` observable of the Propaq TFIM benchmark, placed on the middle qubit of the grid.
"""
tfim2dobservable(nx::Int, ny::Int) = PauliString(nx * ny, :Z, (nx * ny) ÷ 2)

"""
    hubbard2d(nx, ny, nsteps; t=1.0, U=4.0, dt=0.1)

Trotterized time evolution of the 2D Fermi-Hubbard model on an `nx` by `ny` grid,
`H = -t ∑_<ij>,σ (c†_iσ c_jσ + h.c.) + U ∑_i n_i↑ n_i↓`, Jordan-Wigner transformed with the two spin
modes of a site adjacent. Returns the circuit and its parameters.

The hopping terms carry Jordan-Wigner strings, so unlike the Ising circuits this one is generated by
Pauli strings over many qubits at once.
"""
function hubbard2d(nx::Int, ny::Int, nsteps::Int; t::Real=1.0, U::Real=4.0, dt::Real=0.1)
    nq = 2 * nx * ny
    mode(site, spin) = 2 * (site - 1) + spin

    circuit = Gate[]
    thetas = Float64[]

    # c†_p c_q + h.c. = (X_p Z...Z X_q + Y_p Z...Z Y_q) / 2 for p < q
    function hop!(p, q, coeff)
        qinds = collect(p:q)
        for edge in (:X, :Y)
            symbols = fill(:Z, length(qinds))
            symbols[1] = symbols[end] = edge
            push!(circuit, PauliRotation(symbols, qinds))
            push!(thetas, 2 * coeff / 2 * dt)
        end
    end

    # U n_p n_q = U/4 (1 - Z_p - Z_q + Z_p Z_q), dropping the constant
    function interact!(p, q, coeff)
        push!(circuit, PauliRotation([:Z], [p]));    push!(thetas, 2 * (-coeff / 4) * dt)
        push!(circuit, PauliRotation([:Z], [q]));    push!(thetas, 2 * (-coeff / 4) * dt)
        push!(circuit, PauliRotation([:Z, :Z], [p, q])); push!(thetas, 2 * (coeff / 4) * dt)
    end

    for _ in 1:nsteps
        for (site1, site2) in rectangletopology(nx, ny), spin in 1:2
            p, q = minmax(mode(site1, spin), mode(site2, spin))
            hop!(p, q, -t)
        end
        for site in 1:(nx*ny)
            interact!(mode(site, 1), mode(site, 2), U)
        end
    end

    return circuit, thetas
end

"""
    tfi1d(nq, nsteps; theta=0.31)

Trotterized transverse-field Ising evolution on a 1D bricklayer chain, with the same angle on every
gate. This is the reference problem of `propaq-comparison.md`.
"""
function tfi1d(nq::Int, nsteps::Int; theta::Real=0.31)
    circuit = tfitrottercircuit(nq, nsteps; topology=bricklayertopology(nq))
    return circuit, fill(float(theta), countparameters(circuit))
end

"""
    tiltedising(nx, ny, nlayers; dt=0.05, h=1.0, J=0.5)

The circuit of `examples/advanced_performance.ipynb`: Trotterized time evolution of a tilted-field
Ising model on an `nx` by `ny` grid, one layer of `R_x`, `R_z` and nearest-neighbour `R_zz`
rotations per step. Returns the circuit and its parameters.
"""
function tiltedising(nx::Int, ny::Int, nlayers::Int; dt::Real=0.05, h::Real=1.0, J::Real=0.5)
    nq = nx * ny
    layer = PauliRotation[]
    rxlayer!(layer, nq)
    rzlayer!(layer, nq)
    rzzlayer!(layer, rectangletopology(nx, ny))

    thetas = ones(countparameters(layer)) * 2 * dt
    thetas[getparameterindices(layer, PauliRotation, [:X])] .*= h
    thetas[getparameterindices(layer, PauliRotation, [:Z])] .*= h
    thetas[getparameterindices(layer, PauliRotation, [:Z, :Z])] .*= J

    return repeat(layer, nlayers), repeat(thetas, nlayers)
end

"""
    tiltedisingobservable(nx, ny)

The `Z Z` observable of the notebook, on two neighbouring qubits in the middle of the grid.
"""
tiltedisingobservable(nx::Int, ny::Int) = PauliString(nx * ny, [:Z, :Z], [nx * ny ÷ 2 + nx ÷ 2, nx * ny ÷ 2 + nx ÷ 2 + 1])
