module OpenQASMInterface

using OpenQASM
using LinearAlgebra
# Import necessary types from the main PauliPropagation module
import ..PauliPropagation: Gate, CliffordGate, PauliRotation, TGate, TransferMapGate, calculateptm

export readqasm

# Helper to parse numeric parameter tokens from the OpenQASM AST,
# supporting literals and simple unary minus expressions.
function _parse_angle_token(token)
    if hasproperty(token, :str)
        return parse(Float64, getproperty(token, :str))
    elseif token isa OpenQASM.Types.Neg
        return -_parse_angle_token(token.val)
    else
        error("Unsupported numeric expression in QASM parameter: $(typeof(token))")
    end
end

# --- Helper functions for Value-Based Dispatch ---

# Fallback for any gate not explicitly defined
function _translate_gate(gate_name_val::Val{G}, qubits, cargs) where {G}
    gate_name = Symbol(gate_name_val) # Extract symbol from Val type
    error("Unsupported translation for QASM gate: '$(G)'. This operation is not implemented.")
end

# -- Clifford Gates (return gate, nothing for theta) --
_translate_gate(::Val{:h}, qubits, cargs) = (CliffordGate(:H, qubits), nothing)
_translate_gate(::Val{:x}, qubits, cargs) = (CliffordGate(:X, qubits), nothing)
_translate_gate(::Val{:y}, qubits, cargs) = (CliffordGate(:Y, qubits), nothing)
_translate_gate(::Val{:z}, qubits, cargs) = (CliffordGate(:Z, qubits), nothing)
_translate_gate(::Val{:s}, qubits, cargs) = (CliffordGate(:S, qubits), nothing)
_translate_gate(::Val{:sx}, qubits, cargs) = (CliffordGate(:SX, qubits), nothing)
_translate_gate(::Val{:cx}, qubits, cargs) = (CliffordGate(:CNOT, qubits), nothing)
_translate_gate(::Val{:cz}, qubits, cargs) = (CliffordGate(:CZ, qubits), nothing)
_translate_gate(::Val{:swap}, qubits, cargs) = (CliffordGate(:SWAP, qubits), nothing)
_translate_gate(::Val{:t}, qubits, cargs) = (TGate(qubits[1]), nothing)
# Identity gate - do nothing (skip it)
_translate_gate(::Val{:id}, qubits, cargs) = (nothing, nothing)
# Barrier gate - do nothing (skip it, it's just a compiler hint)
_translate_gate(::Val{:barrier}, qubits, cargs) = (nothing, nothing)

# -- Pauli Rotations (return gate, and the parsed theta value) --
function _translate_gate(::Val{:rx}, qubits, cargs)
    theta = _parse_angle_token(cargs[1])
    return (PauliRotation(:X, qubits), theta)
end

function _translate_gate(::Val{:ry}, qubits, cargs)
    theta = _parse_angle_token(cargs[1])
    return (PauliRotation(:Y, qubits), theta)
end

function _translate_gate(::Val{:rz}, qubits, cargs)
    theta = _parse_angle_token(cargs[1])
    return (PauliRotation(:Z, qubits), theta)
end

function _translate_gate(::Val{:p}, qubits, cargs)
    # p(lambda) is equivalent to rz(lambda) - phase gate
    lambda = _parse_angle_token(cargs[1])
    return (PauliRotation(:Z, qubits), lambda)
end

function _translate_gate(::Val{:u1}, qubits, cargs)
    # u1(lambda) is equivalent to a Z rotation RZ(lambda),
    lambda = _parse_angle_token(cargs[1])
    return (PauliRotation(:Z, qubits), lambda)
end

function _translate_gate(::Val{:sdg}, qubits, cargs)
    return (PauliRotation(:Z, qubits), -pi/2)
end

function _translate_gate(::Val{:tdg}, qubits, cargs)
    return (PauliRotation(:Z, qubits), -pi/4)
end

function _translate_gate(::Val{:rzz}, qubits, cargs)
    theta = _parse_angle_token(cargs[1])
    # If angle is pi/2, use the Clifford gate ZZpihalf
    if isapprox(theta, pi/2, atol=1e-10)
        return (CliffordGate(:ZZpihalf, qubits), nothing)
    else
        # Two-qubit ZZ rotation generated by Z ⊗ Z
        return (PauliRotation([:Z, :Z], qubits), theta)
    end
end

function _translate_gate(::Val{:rxx}, qubits, cargs)
    theta = _parse_angle_token(cargs[1])
    # Two-qubit XX rotation generated by X ⊗ X
    return (PauliRotation([:X, :X], qubits), theta)
end

function _translate_gate(::Val{:u3}, qubits, cargs)
    if length(qubits) != 1
        error("u3 gate must act on exactly one qubit, got $(length(qubits)) qubits")
    end
    
    if length(cargs) != 3
        error("u3 gate requires exactly 3 parameters (theta, phi, lambda), got $(length(cargs))")
    end
    
    theta  = _parse_angle_token(cargs[1])
    phi    = _parse_angle_token(cargs[2])
    lambda = _parse_angle_token(cargs[3])
    
    # Compute the u3 unitary matrix
    cos_half_theta = cos(theta / 2)
    sin_half_theta = sin(theta / 2)
    exp_i_lambda = exp(1.0im * lambda)
    exp_i_phi = exp(1.0im * phi)
    exp_i_phi_lambda = exp(1.0im * (phi + lambda))
    
    U = [
        cos_half_theta           -exp_i_lambda * sin_half_theta;
        exp_i_phi * sin_half_theta   exp_i_phi_lambda * cos_half_theta
    ]
    
    # Create TransferMapGate from the unitary matrix
    gate = TransferMapGate(U, qubits)
    
    return (gate, nothing)
end

_translate_gate(::Val{:u}, qubits, cargs) = _translate_gate(Val(:u3), qubits, cargs)

function _translate_gate(::Val{:u2}, qubits, cargs)
    if length(qubits) != 1
        error("u2 gate must act on exactly one qubit, got $(length(qubits)) qubits")
    end

    if length(cargs) != 2
        error("u2 gate requires exactly 2 parameters (phi, lambda), got $(length(cargs))")
    end

    theta = pi/2
    phi = _parse_angle_token(cargs[1])
    lambda = _parse_angle_token(cargs[2])

    # Compute the corresponding u3-style unitary matrix
    cos_half_theta = cos(theta / 2)
    sin_half_theta = sin(theta / 2)
    exp_i_lambda = exp(1.0im * lambda)
    exp_i_phi = exp(1.0im * phi)
    exp_i_phi_lambda = exp(1.0im * (phi + lambda))

    U = [
        cos_half_theta           -exp_i_lambda * sin_half_theta;
        exp_i_phi * sin_half_theta   exp_i_phi_lambda * cos_half_theta
    ]

    gate = TransferMapGate(U, qubits)
    return (gate, nothing)
end

# -- Composite Gates (return vector of gates) --

function _translate_gate(::Val{:sxdg}, qubits, cargs)
    # sxdg = { s a; h a; s a; } - inverse sqrt(X)
    gates = [CliffordGate(:S, qubits), CliffordGate(:H, qubits), CliffordGate(:S, qubits)]
    thetas = [nothing, nothing, nothing]
    return (gates, thetas)
end

function _translate_gate(::Val{:cy}, qubits, cargs)
    a, b = qubits
    gates  = [PauliRotation(:Z, b), CliffordGate(:CNOT, [a, b]), PauliRotation(:Z, b)]
    # First gate = S† ≃ RZ(-π/2), last gate = S ≃ RZ(π/2).
    thetas = [-pi/2,           nothing,                       pi/2]
    return (gates, thetas)
end

function _translate_gate(::Val{:ch}, qubits, cargs)
    # ch = controlled-H (complex decomposition)
    a, b = qubits
    gates = [
        CliffordGate(:H, b),
        PauliRotation(:Z, b),  # sdg
        CliffordGate(:CNOT, [a, b]),
        CliffordGate(:H, b),
        TGate(b),
        CliffordGate(:CNOT, [a, b]),
        TGate(b),
        CliffordGate(:H, b),
        CliffordGate(:S, b),
        CliffordGate(:X, b),
        CliffordGate(:S, a)
    ]
    thetas = [nothing, -pi/2, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing]
    return (gates, thetas)
end

function _translate_gate(::Val{:ccx}, qubits, cargs)
    # ccx = Toffoli gate (complex decomposition)
    a, b, c = qubits
    gates = [
        CliffordGate(:H, c),
        CliffordGate(:CNOT, [b, c]),
        PauliRotation(:Z, c),  # tdg
        CliffordGate(:CNOT, [a, c]),
        TGate(c),
        CliffordGate(:CNOT, [b, c]),
        PauliRotation(:Z, c),  # tdg
        CliffordGate(:CNOT, [a, c]),
        TGate(b),
        TGate(c),
        CliffordGate(:H, c),
        CliffordGate(:CNOT, [a, b]),
        TGate(a),
        PauliRotation(:Z, b),  # tdg
        CliffordGate(:CNOT, [a, b])
    ]
    thetas = [nothing, nothing, -pi/4, nothing, nothing, nothing, -pi/4, nothing, nothing, nothing, nothing, nothing, nothing, -pi/4, nothing]
    return (gates, thetas)
end

function _translate_gate(::Val{:cswap}, qubits, cargs)
    # cswap = controlled-SWAP (Fredkin gate) = { cx c,b; ccx a,b,c; cx c,b; }
    a, b, c = qubits
    # First cx c,b
    gates = Gate[CliffordGate(:CNOT, [c, b])]
    thetas = Union{Nothing, Float64}[nothing]
    # Then ccx a,b,c (expands to 15 gates with 3 thetas)
    ccx_gates, ccx_thetas = _translate_gate(Val(:ccx), [a, b, c], cargs)
    append!(gates, ccx_gates)
    append!(thetas, ccx_thetas)
    # Finally cx c,b
    push!(gates, CliffordGate(:CNOT, [c, b]))
    push!(thetas, nothing)
    return (gates, thetas)
end

function _translate_gate(::Val{:crx}, qubits, cargs)
    # crx(lambda) = controlled RX rotation
    # { u1(pi/2) b; cx a,b; u3(-lambda/2,0,0) b; cx a,b; u3(lambda/2,-pi/2,0) b; }
    a, b = qubits
    lambda = _parse_angle_token(cargs[1])

    gates = Gate[
        PauliRotation(:Z, b),           # u1(pi/2) = rz(pi/2)
        CliffordGate(:CNOT, [a, b]),    # cx a,b
        PauliRotation(:Y, b),           # u3(-lambda/2,0,0) = ry(-lambda/2)
        CliffordGate(:CNOT, [a, b])     # cx a,b
    ]
    thetas = Union{Nothing, Float64}[pi/2, nothing, -lambda/2, nothing]

    # Final single-qubit gate: u3(lambda/2,-pi/2,0) on b.
    # Use the closed-form u3 matrix to build a TransferMapGate directly.
    theta_u3  = lambda / 2
    phi_u3    = -pi/2
    lambda_u3 = 0.0

    cos_half = cos(theta_u3 / 2)
    sin_half = sin(theta_u3 / 2)
    exp_i_lambda_u3 = exp(1.0im * lambda_u3)          # = 1
    exp_i_phi_u3    = exp(1.0im * phi_u3)             # = -im
    exp_i_phi_lambda_u3 = exp(1.0im * (phi_u3 + lambda_u3))

    U_u3 = [
        cos_half                 -exp_i_lambda_u3 * sin_half;
        exp_i_phi_u3 * sin_half   exp_i_phi_lambda_u3 * cos_half
    ]

    push!(gates, TransferMapGate(U_u3, [b]))
    push!(thetas, nothing)

    return (gates, thetas)
end

function _translate_gate(::Val{:cry}, qubits, cargs)
    # cry(lambda) = controlled RY rotation
    # { ry(lambda/2) b; cx a,b; ry(-lambda/2) b; cx a,b; }
    a, b = qubits
    lambda = _parse_angle_token(cargs[1])

    gates = [
        PauliRotation(:Y, b),
        CliffordGate(:CNOT, [a, b]),
        PauliRotation(:Y, b),
        CliffordGate(:CNOT, [a, b])
    ]
    thetas = [lambda/2, nothing, -lambda/2, nothing]
    return (gates, thetas)
end

function _translate_gate(::Val{:crz}, qubits, cargs)
    # crz(lambda) = controlled RZ rotation
    # { rz(lambda/2) b; cx a,b; rz(-lambda/2) b; cx a,b; }
    a, b = qubits
    lambda = _parse_angle_token(cargs[1])

    gates = [
        PauliRotation(:Z, b),
        CliffordGate(:CNOT, [a, b]),
        PauliRotation(:Z, b),
        CliffordGate(:CNOT, [a, b])
    ]
    thetas = [lambda/2, nothing, -lambda/2, nothing]
    return (gates, thetas)
end

function _translate_gate(::Val{:cu}, qubits, cargs)
    a, b = qubits
    if length(qubits) != 2
        error("cu gate must act on exactly two qubits, got $(length(qubits)) qubits")
    end
    if length(cargs) != 4
        error("cu gate requires exactly 4 parameters (theta, phi, lambda, gamma), got $(length(cargs))")
    end

    theta  = _parse_angle_token(cargs[1])
    phi    = _parse_angle_token(cargs[2])
    lambda = _parse_angle_token(cargs[3])
    gamma  = _parse_angle_token(cargs[4])

    # Helper to build a single-qubit U3 matrix (same convention as the u3 translation).
    u3_matrix(theta, phi, lambda) = begin
        cos_half = cos(theta / 2)
        sin_half = sin(theta / 2)
        exp_i_lambda = exp(1.0im * lambda)
        exp_i_phi = exp(1.0im * phi)
        exp_i_phi_lambda = exp(1.0im * (phi + lambda))
        [
            cos_half                 -exp_i_lambda * sin_half;
            exp_i_phi * sin_half      exp_i_phi_lambda * cos_half
        ]
    end

    theta1, phi1, lambda1 = -theta/2, 0.0, -(phi + lambda)/2
    theta2, phi2, lambda2 =  theta/2,  phi, 0.0

    U1 = u3_matrix(theta1, phi1, lambda1)
    U2 = u3_matrix(theta2, phi2, lambda2)

    gates = Gate[
        # p(gamma) on control
        PauliRotation(:Z, a),
        # p((lambda+phi)/2) on control
        PauliRotation(:Z, a),
        # p((lambda-phi)/2) on target
        PauliRotation(:Z, b),
        CliffordGate(:CNOT, [a, b]),
        TransferMapGate(U1, [b]),
        CliffordGate(:CNOT, [a, b]),
        TransferMapGate(U2, [b]),
    ]

    thetas = [
        gamma,
        (lambda + phi)/2,
        (lambda - phi)/2,
        nothing,
        nothing,
        nothing,
        nothing,
    ]

    return (gates, thetas)
end

function _translate_gate(::Val{:cu3}, qubits, cargs)
    a, b = qubits
    if length(cargs) != 3
        error("cu3 gate requires exactly 3 parameters (theta, phi, lambda), got $(length(cargs))")
    end

    theta  = _parse_angle_token(cargs[1])
    phi    = _parse_angle_token(cargs[2])
    lambda = _parse_angle_token(cargs[3])

    # Helper to build a single-qubit U3 matrix (same convention as u3 translation).
    u3_matrix(theta, phi, lambda) = begin
        cos_half = cos(theta / 2)
        sin_half = sin(theta / 2)
        exp_i_lambda = exp(1.0im * lambda)
        exp_i_phi = exp(1.0im * phi)
        exp_i_phi_lambda = exp(1.0im * (phi + lambda))
        [
            cos_half                 -exp_i_lambda * sin_half;
            exp_i_phi * sin_half      exp_i_phi_lambda * cos_half
        ]
    end

    # Parameters for the two U3 blocks on the target.
    theta1, phi1, lambda1 = -theta/2, 0.0, -(phi + lambda)/2
    theta2, phi2, lambda2 =  theta/2,  phi, 0.0

    U1 = u3_matrix(theta1, phi1, lambda1)
    U2 = u3_matrix(theta2, phi2, lambda2)

    gates = Gate[
        # u1((lambda+phi)/2) a  -> RZ on control
        PauliRotation(:Z, a),
        # u1((lambda-phi)/2) b  -> RZ on target
        PauliRotation(:Z, b),
        CliffordGate(:CNOT, [a, b]),
        TransferMapGate(U1, [b]),
        CliffordGate(:CNOT, [a, b]),
        TransferMapGate(U2, [b]),
    ]

    thetas = [
        (lambda + phi)/2,
        (lambda - phi)/2,
        nothing,
        nothing,
        nothing,
        nothing,
    ]

    return (gates, thetas)
end

function _translate_gate(::Val{:cu1}, qubits, cargs)
    a, b = qubits
    lambda = _parse_angle_token(cargs[1])

    gates = [
        PauliRotation(:Z, a),
        CliffordGate(:CNOT, [a, b]),
        PauliRotation(:Z, b),
        CliffordGate(:CNOT, [a, b]),
        PauliRotation(:Z, b)
    ]
    thetas = [lambda/2, nothing, -lambda/2, nothing, lambda/2]
    return (gates, thetas)
end

function _translate_gate(::Val{:cp}, qubits, cargs)
    a, b = qubits
    lambda = _parse_angle_token(cargs[1])

    gates = [
        PauliRotation(:Z, a),
        CliffordGate(:CNOT, [a, b]),
        PauliRotation(:Z, b),
        CliffordGate(:CNOT, [a, b]),
        PauliRotation(:Z, b)
    ]
    thetas = [lambda/2, nothing, -lambda/2, nothing, lambda/2]
    return (gates, thetas)
end

function _translate_gate(::Val{:csx}, qubits, cargs)
    # csx = { h b; cu1(pi/2) a,b; h b; }
    a, b = qubits
    # cu1(pi/2): use lambda = pi/2
    lambda = pi/2
    gates = [
        CliffordGate(:H, b),
        PauliRotation(:Z, a),
        CliffordGate(:CNOT, [a, b]),
        PauliRotation(:Z, b),
        CliffordGate(:CNOT, [a, b]),
        PauliRotation(:Z, b),
        CliffordGate(:H, b),
    ]
    thetas = [nothing, lambda/2, nothing, -lambda/2, nothing, lambda/2, nothing]
    return (gates, thetas)
end

function _translate_gate(::Val{:c3x}, qubits, cargs)
    # c3x = 3-controlled X gate (non-relative-phase)
   
    gate_name_val = Val(:c3x)
    error("Unsupported translation for QASM gate: 'c3x'. This operation is not implemented.")
end


"""
    readqasm(filepath::String) -> (Int, Vector, Vector)

Parses an OpenQASM 2.0 file and returns the number of qubits, 
a circuit compatible with PauliPropagation.jl, and a vector of gate parameters (thetas).
"""
function readqasm(filepath::String)
    qasm_content = read(filepath, String)
    parsed_program = OpenQASM.parse(qasm_content)

    statements = parsed_program.prog

    # Find the qreg declaration to determine the number of qubits
    nq = 0
    qreg_decl_idx = findfirst(x -> x isa OpenQASM.Types.RegDecl, statements)
    if qreg_decl_idx !== nothing
        size_token = statements[qreg_decl_idx].size
        nq = parse(Int, size_token.str)
    else
        error("QASM file does not contain a qubit register ('qreg') declaration.")
    end

    circuit = []
    thetas = []

    # Loop through every instruction in the extracted list
    for instruction in statements
        # Handle reset and measure as special cases (they're not Instruction types)
        if instruction isa OpenQASM.Types.Reset
            error("Unsupported translation for QASM gate: 'reset'. Reset operations are non-unitary and not supported.")
        elseif instruction isa OpenQASM.Types.Measure
            error("Unsupported translation for QASM gate: 'measure'. Measurement operations are non-unitary and not supported.")
        elseif !(instruction isa OpenQASM.Types.Instruction)
            continue
        end

        gate_name_str = instruction.name
        qubits = [parse(Int, q.address.str) + 1 for q in instruction.qargs]
        cargs = instruction.cargs

        # Convert the gate name string to a Val{Symbol} to enable multiple dispatch
        gate_name_val = Val(Symbol(gate_name_str))

        # Dispatch to the correct helper method based on the gate name
        result = _translate_gate(gate_name_val, qubits, cargs)

        # Handle both single gates and vectors of gates (for composite gates)
        if result isa Tuple && result[1] isa Vector
            # Composite gate: result is (Vector{gate}, Vector{theta or nothing})
            gate_vec, theta_vec = result
            for (i, g) in enumerate(gate_vec)
                if isnothing(g)
                    continue  # Skip identity gates in composite
                end
                push!(circuit, g)
                if i <= length(theta_vec) && !isnothing(theta_vec[i])
                    push!(thetas, theta_vec[i])
                end
            end
        else
            # Single gate: original behavior (gate, theta)
            gate_obj, theta = result
            # Skip gates that return nothing (e.g., identity gate)
            if isnothing(gate_obj)
                continue
            end
            push!(circuit, gate_obj)
            if !isnothing(theta)
                push!(thetas, theta)
            end
        end
    end

    return nq, circuit, thetas
end

end # end of module